package stuffplotter.signals;

import com.google.gwt.event.shared.GwtEvent;

/**
 * Event that gets fired when an event is successfully created.
 */
public class EventCreatedEvent extends GwtEvent<EventCreatedEventHandler>
{
	public static Type<EventCreatedEventHandler> TYPE = new Type<EventCreatedEventHandler>();
	private final Long eventID;
	
	/**
	 * Constructor for an EventCreatedEvent.
	 * @pre true;
	 * @post true;
	 * @param eventID - the ID of the event auto-generated by the server.
	 */
	public EventCreatedEvent(Long eventID)
	{
		this.eventID = eventID;
	}
	
	/**
	 * Retrieve the ID for the event that was created.
	 * @pre true;
	 * @post true;
	 * @return the ID for the event that was created.
	 */
	public Long getEventID()
	{
		return this.eventID;
	}
	
	@Override
	public Type<EventCreatedEventHandler> getAssociatedType()
	{
		return TYPE;
	}

	@Override
	protected void dispatch(EventCreatedEventHandler handler)
	{
		handler.onEventCreated(this);
	}
}
